[general]
live_config_reload = true
import = [
  "/home/eggbert/.config/alacritty/ashen.toml"
]

[window]
padding.x = 5
padding.y = 5

[font]
size = 12
normal.family = "IosevkaTerm NFM"
# normal.family = "Monocraft"

[cursor]
vi_mode_style = { shape = "Block", blinking = "On" }
